### ISSUE TITLE
On going project development & support

### ISSUE THREAD

**Issue by JoeAlamo** [awslabs/fargatecli#105]
Hi there,

My organisation are moving towards Docker and want to use ECS Fargate. Whilst we would use CloudFormation to manage the setting up of the infrastructure & ECS services etc. this CLI looks fantastic for developers to use, to get info on what is running, view logs, run one off tasks etc. 

However, I recently came across the ECS CLI v2. 

I would like to know where this fargatecli project stands in terms of future development & support?

Is it going to be sidelined in favour of the ECS CLI v2? Or can I safely start to invest in adoption of this tool?

Many thanks.

**Comment by jritsema** [comment]
fwiw, [our fork](https://github.com/turnerlabs/fargate) is actively maintained.  This approach has worked well for us, however, we use [terraform](https://github.com/turnerlabs/fargate-create#stacks) instead of cloud formation.

https://github.com/turnerlabs/fargate-create

**Comment by PaulMaddox** [comment]
Hi, AWS employee and one of the Fargate CLI maintainers here. We are putting a lot of investment into the AWS CLI v2 and I think that is probably the better route to take.

**Comment by jufemaiz** [comment]
@PaulMaddox perhaps it would be advisable to place a notice that this particular repo is no longer under active development and will be maintained only on a continuity of service level?

**Comment by PaulMaddox** [comment]
Added a clarification notice to the README - aa1c09cd404ecdee91a83b4f59171f790d6b480b

AWS Copilot is the better option these days, and is actively maintained by the AWS Containers team. 

Thanks all.

**Comment by jufemaiz** [comment]
Thanks @PaulMaddox for the fast response!
