### ISSUE TITLE
fargatecli to support the China region

### ISSUE THREAD

**Issue by liangruibupt** [awslabs/fargatecli#110]
fargate lb create order-lb --port 80 --region cn-northwest-1
[!] Invalid region: cn-northwest-1 [valid regions: ap-northeast-1, ap-northeast-2, ap-south-1, ap-southeast-1, ap-southeast-2, ca-central-1, eu-central-1, eu-west-1, eu-west-2, us-east-1, us-east-2, us-west-1, us-west-2]

Fargate has been launched in China regions, please add this support

**Comment by bnusunny** [comment]
@liangruibupt The latest release already support China regions. :)

```bash
8c85909aaff7:~ sunhua$ fargate --version
fargate version 0.3.2
8c85909aaff7:~ sunhua$ fargate lb create order-lb --port 80 --region cn-northwest-1
 ℹ️  Created load balancer order-lb
```
