### ISSUE TITLE
Can't add environment variable that contains a comma

### ISSUE THREAD

**Issue by jrtilson** [awslabs/fargatecli#40]
If we enter:

`fargate service env set myapp --env MY_VAR=has,comma`

The result is:

`[!] Invalid environment variable`
`comma must be in the form of KEY=value`

This is an issue because I'm trying to supply a mongodb string, ie:

`MONGO_URL=mongodb://user:pass@host1,host2/db?auth=123&key=456`

Can the `value` portion be escaped somehow?

**Comment by abarfoot** [comment]
Possible workaround:  When the value is a url, try substituting %2c for the comma.

**Comment by gr3w2** [comment]
> Possible workaround: When the value is a url, try substituting %2c for the comma.

Unfortunately, it not works. Somehow `%2c` is replaced by space symbol.
Also, I found that if I specify ENV variables like `--env MY_VAR_1=1,MY_VAR_2=2`, then fargate cli deploy it as 2 separate variables.

**Comment by holyjak** [comment]
It seems pretty easy to fix according to https://github.com/turnerlabs/fargate/commit/f2fe902664045c135f37eca877e717f4b3c345e4, replacing `Flags().StringSliceVarP` with `Flags().StringArrayVarP`. Could it be done? Please? 🙏

**Comment by PaulMaddox** [comment]
Merged :)
