### ISSUE TITLE
Version specification is shown incorrect

### ISSUE THREAD

**Issue by nuttikung** [awslabs/fargatecli#86]
I have downloaded fargate-cli version 0.3.1 from [this](https://github.com/jpignata/fargate/releases)

![Screen Shot 2019-05-16 at 11 10 13](https://user-images.githubusercontent.com/8456620/57825913-356e5380-77cb-11e9-89af-c1c50ad534e2.png)

Then use a command to verify version as 

> $ fargate --version

The result is shown as below :
>  fargate version 0.3.0

**Comment by nodesocket** [comment]
Just opened a PR https://github.com/jpignata/fargate/pull/91

**Comment by PaulMaddox** [comment]
Fixed in v0.3.2
