### ISSUE TITLE
default region cannot be changed

### ISSUE THREAD

**Issue by nishanbrown** [awslabs/fargatecli#95]
Getting error with default region when using anything else other than ``us-east-1``:
``fargate task run dev-webapp --cluster dev --region us-west-2``
``[!] Invalid region: us-west-2 [valid regions: us-east-1]``

Tried export the default region:
``export AWS_DEFAULT_REGION=us-west-2``

Also tried adding ``us-west-2`` as a default region in AWS configuration and still got the same error.

**Comment by PaulMaddox** [comment]
Fixed in v0.3.2
